name: Publish PIPE Binaries

on:
  push:
    branches:
      - main
    paths:
      - VERSION

permissions:
  contents: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Test
        run: go test ./...

      - run: |
          echo "Publishing version $(cat VERSION)"
          git config --global user.email "pipeline@r2p.dev"
          git config --global user.name "Pipeline"
          git tag -a -m "Release $(cat VERSION)" $(cat VERSION)
          git push origin $(cat VERSION)
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
